
### GET /
GET http://127.0.0.1:3000/

### GET /items
GET http://127.0.0.1:3000/items

### GET /items/:id
GET http://127.0.0.1:3000/items/23

### POST new item
POST http://127.0.0.1:3000/items
content-type: application/json

{"name": "kurkku"}

### POST error data
POST http://127.0.0.1:3000/items
content-type: application/json


### DELETE /items/:id
DELETE http://127.0.0.1:3000/items


### PUT /items/:id
PUT http://127.0.0.1:3000/items


{"not_data": "not_data"}

